spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/intelli_note?useSSL=false&allowPublicKeyRetrieval=true"
    username: "your username"
    password: "your password"
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    locations: classpath:database
  elasticsearch:
    uris: "https://www.elasticsearch.co:9200"
    username: "your username"
    password: "your password"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "your username"
    password: "your password"
    virtual-host: "intelli-note" # your rabbitmq virtual host

oss:
  access-key: "your access-key"
  secret-key: "your secret-key"
  bucket: "your bucket"
  region: "your bucket region id" # https://developer.qiniu.com/kodo/1671/region-endpoint-fq
  domain: "your domain (e.g., domain.example.com)"

minio:
  access-key: "your access-key"
  secret-key: "your secret-key"
  endpoint: "www.minio.io" # your minio server endpoint
  bucket: "your bucket"

aliyun:
  access-key: "your access-key"
  secret-key: "your secret-key"
  nls:
    app-key: "your nls project app-key"

mini-program:
  app-id: "your mini program's AppID"
  app-secret: "your mini program's AppSecret"