spring:
  application:
    name: "intelli-note"
  profiles:
    active:
      - dev
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: "/api"

logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"