name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Junit Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.1.4
      # - name: Setup JDK 17
      #   uses: actions/setup-java@v4.2.1
      - name: Check JDK Version
      - run: java --version
        
      
    
