name: Test

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'

jobs:
  test:
    name: Run Project Unit Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.1.4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4.2.1
        with: 
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
        
      - name: Run Junit Test
        run: mvn -B clean test
